[env:xiao_esp32s3_dv2]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
upload_port = COM6
monitor_port = COM6
monitor_speed = 115200
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
